
name: Docs

on:
    push:
        branches:
            - main
permissions:
  id-token: write
  contents: write # Optionally, if your deployment needs to push changes
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install sphinx
        # pip install pydata-sphinx-theme
        # pip install sphinx-design
        # pip install sphinx-togglebutton
        # pip install sphinxcontrib-mermaid
        # pip install graphviz
        pip install .[docs]
    - name: Install additional dependencies
      run: |
        sudo apt-get install -y graphviz
    - name: Build documentation
      id: build
      run: |
        cd docs
        make clean
        make html
        ls _build/html
        ls _build/html/_images/
    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: documentation
    #     path: |
    #       docs/_build/html/
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
      with:
        path: docs/_build/html/

    # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4